# Generated by Django 3.1.1 on 2020-09-30 13:57

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authapp', '0003_auto_20200930_1857'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(max_length=25, null=True)),
                ('task_description', models.CharField(max_length=250, null=True)),
                ('created_at', models.DateTimeField(default=datetime.datetime(2020, 9, 30, 13, 57, 2, 549223, tzinfo=utc))),
                ('task_status', models.CharField(choices=[('N', 'New'), ('P', 'Planned'), ('W', 'Working'), ('F', 'Finished')], max_length=1)),
                ('task_finished_date', models.DateTimeField(null=True)),
                ('task_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authapp.user')),
            ],
        ),
    ]
