# Generated by Django 3.1.1 on 2020-09-30 14:10

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('taskapp', '0002_auto_20200930_1904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 30, 14, 10, 35, 213012, tzinfo=utc)),
        ),
    ]
