# Generated by Django 3.1.1 on 2020-10-01 13:43

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('taskapp', '0018_auto_20200930_2134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 1, 13, 43, 14, 727991, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='TaskLogger',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=datetime.datetime(2020, 10, 1, 13, 43, 14, 728961, tzinfo=utc))),
                ('task_changes', models.CharField(max_length=250, null=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='taskapp.task')),
            ],
        ),
    ]
