# Generated by Django 3.1.1 on 2020-10-01 15:46

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('taskapp', '0019_auto_20201001_1843'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasklogger',
            name='task_name',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 1, 15, 46, 52, 210812, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='tasklogger',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 1, 15, 46, 52, 211808, tzinfo=utc)),
        ),
    ]
