# Generated by Django 3.1.1 on 2020-09-30 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email_login', models.EmailField(max_length=78, unique=True)),
                ('token_activation', models.CharField(max_length=250, null=True)),
                ('token_life', models.DateTimeField(null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
