# Generated by Django 3.1.1 on 2020-09-30 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0002_user_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='token_activation',
        ),
        migrations.RemoveField(
            model_name='user',
            name='token_life',
        ),
    ]
