# Generated by Django 3.1.1 on 2020-09-30 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0005_auto_20200930_1910'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='username',
            new_name='email',
        ),
    ]
