# Generated by Django 3.1.1 on 2020-09-30 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0007_user_auth_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='auth_token',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
