# Generated by Django 3.1.1 on 2020-09-30 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0011_auto_20200930_2012'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='auth_token',
        ),
    ]
