# Generated by Django 3.1.1 on 2020-09-30 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0013_auto_20200930_2100'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
        migrations.RenameField(
            model_name='user',
            old_name='email',
            new_name='username',
        ),
    ]
