# Generated by Django 3.1.1 on 2020-09-30 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0015_auto_20200930_2111'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
    ]
